
data_folder: "/Users/lviotti/Library/CloudStorage/Dropbox/Work/Kitzes/datasets/sine2023terr"

# audio-moth or smm
aru_type: smm 

# filename for deployment sheet in data_folder
deployment_sheet: sine2023_terrestrial.csv 

# Sheet columns
pickup_time_column: "pickup:EditDate"
deployment_time_column: "dropoff:EditDate" 
subdirectories_column: recorder_code

# Sheet date format
datetime_format_str : '%m/%d/%y %H:%M'

# types of files to check for in/out of deployment period
glob_patterns: ['*.mp3', '*.wav','*.WAV']

# Add a delay in hours to deployment time and subtract from pickup time.
buffer_hours: null

# Parallelize with Joblib.Parallel and delayed
parallel_jobs: 8